export type ExerciseCategory =
  | "lengan"
  | "bisep"
  | "tricep"
  | "bahu"
  | "dada"
  | "punggung"
  | "perut"
  | "kaki"
  | "kardio"
  | "fullbody";

export type Equipment =
  | "tanpa alat"
  | "botol air / dumbbell"
  | "resistance band"
  | "kursi / meja"
  | "matras"
  | "hand grip";

export type AlternatifTanpaAlat = {
  nama: string;
  deskripsi: string;
  langkah: string[];
  videoEmbedId?: string;
};

export type Exercise = {
  id: string;
  nama: string;
  kategori: ExerciseCategory[];
  alat: Equipment[];
  deskripsi: string;
  langkah: string[];
  kesalahanUmum?: string[];
  tips: string[];
  kesalahanUmum?: string[];
  videoUrl?: string;
  /** YouTube video ID (just the ID, not full URL) — used for embed player */
  videoEmbedId?: string;
  gambar?: string;
  /** Used for Personal Records: if defined, this is the metric tracked */
  prMetric?: "reps" | "durasi-detik";
  /** Alternative exercise without furniture (kursi/meja) */
  alternatifTanpaAlat?: AlternatifTanpaAlat;
};

export const EXERCISES: Exercise[] = [
  {
    id: "push-up",
    nama: "Push-up Standar",
    kategori: ["dada", "lengan", "tricep", "bahu"],
    alat: ["tanpa alat", "matras"],
    deskripsi:
      "Latihan klasik untuk membentuk dada, lengan, bahu, dan tricep. Wajib untuk pemula.",
    langkah: [
      "POSISI AWAL: Berlutut di lantai/matras, taruh kedua telapak tangan di lantai selebar bahu atau sedikit lebih lebar.",
      "Langkahkan kaki ke belakang satu per satu sampai tubuh lurus dari kepala hingga tumit — seperti posisi plank.",
      "Jari-jari tangan membuka lebar, tangan mengarah sedikit ke luar (~45°). Berat badan tertumpu di telapak tangan dan ujung kaki.",
      "Kencangkan perut (bayangkan perut mau kena pukul), kencangkan bokong — ini menjaga tubuh lurus.",
      "TURUN: Tarik napas. Tekuk kedua siku secara perlahan, turunkan dada menuju lantai. Siku membentuk sudut ~45° dari badan (jangan terlalu lebar).",
      "Turunkan sampai dada berjarak 5-10 cm dari lantai, atau sampai lengan atas sejajar dengan lantai.",
      "Jeda sebentar di posisi bawah (1 detik) — rasakan regangan di dada.",
      "NAIK: Buang napas kuat, dorong lantai dengan kedua tangan. Luruskan siku sampai posisi awal.",
      "Di posisi atas, pastikan siku tidak dikunci penuh (sedikit ditekuk) untuk menjaga tegangan otot.",
      "Ulangi gerakan turun-naik dengan tempo 2 detik turun, 1 detik naik.",
      "SELESAI: Setelah semua rep, turunkan lutut ke lantai dengan terkontrol, lalu duduk ke posisi istirahat.",
    ],
    kesalahanUmum: [
      "Pinggul turun (sagging) — perut kurang kencang. Solusi: kencangkan core & bokong.",
      "Pinggul naik terlalu tinggi — badan membentuk A. Solusi: bayangkan garis lurus dari kepala ke tumit.",
      "Siku terlalu lebar (90°) — bahaya untuk bahu. Solusi: jaga siku 45° dari badan.",
      "Kepala menunduk atau mendongak — Solusi: pandangan ke lantai ~30 cm di depan tangan.",
      "Gerakan terlalu cepat tanpa kontrol — Solusi: hitung 2 detik turun, 1 detik naik.",
    ],
    tips: [
      "Belum kuat? Mulai dari knee push-up (lutut menempel lantai).",
      "Atau push-up dengan tangan di atas meja/kursi untuk versi lebih ringan.",
      "Fokus pada bentuk, bukan jumlah. 5 push-up bagus lebih baik dari 15 yang asal.",
    ],
    videoUrl: "https://www.youtube.com/results?search_query=cara+push+up+benar+pemula",
    videoEmbedId: "IODxDxX7oi4",
    prMetric: "reps",
  },
  {
    id: "knee-push-up",
    nama: "Knee Push-up",
    kategori: ["dada", "lengan", "tricep"],
    alat: ["tanpa alat", "matras"],
    deskripsi:
      "Versi push-up untuk pemula. Lutut menempel di lantai sebagai tumpuan, mengurangi beban ~40%.",
    langkah: [
      "POSISI AWAL: Berlutut di matras/lantai. Taruh kedua tangan di lantai selebar bahu.",
      "Geser tangan sedikit ke depan hingga badan membentuk garis lurus dari kepala sampai lutut (bukan dari kepala ke kaki).",
      "Silangkan pergelangan kaki di belakang agar posisi stabil, atau biarkan kaki rata di lantai.",
      "Kencangkan perut dan bokong — jangan biarkan pinggul turun.",
      "TURUN: Tarik napas, tekuk siku perlahan. Turunkan dada ke arah lantai dengan sudut siku ~45° dari badan.",
      "Turunkan sampai dada hampir menyentuh lantai (5-10 cm).",
      "Jeda 1 detik di posisi bawah.",
      "NAIK: Buang napas, dorong lantai dengan kuat sampai siku hampir lurus.",
      "Jaga agar gerakan terkontrol — 2 detik turun, 1 detik naik.",
      "SELESAI: Setelah semua rep selesai, duduk ke posisi berlutut untuk istirahat.",
    ],
    kesalahanUmum: [
      "Pinggul turun sehingga hanya dada yang bergerak — Solusi: kencangkan core, jaga garis lurus dari kepala ke lutut.",
      "Tangan terlalu ke depan — beban jadi ke bahu, bukan dada. Solusi: tangan tepat di bawah bahu.",
      "Siku terlalu terbuka — bahaya bahu. Solusi: siku ~45° dari badan.",
    ],
    tips: [
      "Cocok kalau push-up standar masih terlalu berat.",
      "Setelah bisa 3 set x 12 reps dengan nyaman, naik ke push-up standar.",
    ],
    videoUrl: "https://www.youtube.com/results?search_query=knee+push+up+tutorial",
    videoEmbedId: "jWxvty2KROs",
    prMetric: "reps",
  },
  {
    id: "diamond-push-up",
    nama: "Diamond Push-up",
    kategori: ["tricep", "dada"],
    alat: ["tanpa alat", "matras"],
    deskripsi:
      "Push-up dengan posisi tangan rapat membentuk berlian. Fokus utama ke tricep (belakang lengan).",
    langkah: [
      "POSISI AWAL: Mulai dari posisi push-up. Geser kedua tangan ke tengah sampai ibu jari dan telunjuk saling menyentuh membentuk berlian/segitiga.",
      "Posisi tangan sejajar dengan dada (bukan di depan wajah).",
      "Kaki selebar bahu untuk stabilitas. Tubuh lurus dari kepala sampai tumit.",
      "Kencangkan perut dan bokong.",
      "TURUN: Tarik napas. Tekuk siku — siku akan secara alami mengarah ke belakang (bukan ke samping seperti push-up biasa).",
      "Turunkan dada sampai hampir menyentuh tangan. Rasakan regangan kuat di tricep.",
      "Jeda 1 detik di bawah.",
      "NAIK: Buang napas, dorong tangan ke lantai dengan fokus pada tricep. Kembali ke posisi atas.",
      "Jangan kunci siku di posisi atas — jaga sedikit bengkok untuk tegangan konstan.",
      "SELESAI: Turunkan lutut, istirahat. Shake out pergelangan tangan jika perlu.",
    ],
    kesalahanUmum: [
      "Siku terbuka ke samping — Solusi: biarkan siku mengarah ke belakang secara alami.",
      "Tangan di depan wajah — Solusi: taruh tangan sejajar dada.",
      "Range of motion terlalu pendek — Solusi: turun sampai dada nyaris sentuh tangan.",
    ],
    tips: [
      "Versi lebih sulit dari push-up standar — kuasai dulu push-up biasa.",
      "Boleh dilakukan dengan lutut menempel kalau masih berat.",
    ],
    videoEmbedId: "J0DnG1_S92I",
    prMetric: "reps",
  },
  {
    id: "pike-push-up",
    nama: "Pike Push-up",
    kategori: ["bahu"],
    alat: ["tanpa alat", "matras"],
    deskripsi:
      "Push-up dengan pinggul terangkat tinggi (seperti V terbalik). Sangat efektif untuk bahu.",
    langkah: [
      "POSISI AWAL: Mulai dari posisi push-up standar.",
      "Jalan kaki ke depan sambil angkat pinggul tinggi — tubuh membentuk huruf V terbalik (seperti downward dog dalam yoga).",
      "Tangan selebar bahu atau sedikit lebih lebar. Kaki bisa lurus atau sedikit ditekuk tergantung fleksibilitas.",
      "Kepala di antara kedua lengan, pandangan ke arah kaki.",
      "TURUN: Tarik napas. Tekuk siku, turunkan bagian atas kepala menuju lantai di antara kedua tangan.",
      "Siku mengarah ke belakang-samping (~45°). Turunkan sampai kepala hampir menyentuh lantai.",
      "Jeda 1 detik di bawah.",
      "NAIK: Buang napas, dorong dengan kuat kembali ke posisi V terbalik.",
      "Pastikan dorongan datang dari bahu, bukan dari punggung.",
      "SELESAI: Setelah set selesai, jalan kaki ke belakang ke posisi plank, lalu turunkan lutut.",
    ],
    kesalahanUmum: [
      "Pinggul tidak cukup tinggi — jadi mirip push-up biasa. Solusi: naikkan pinggul lebih tinggi.",
      "Siku terbuka lebar — beban berlebih ke sendi bahu. Solusi: siku 45° ke belakang.",
      "Leher tegang — Solusi: rilekskan leher, biarkan kepala menggantung alami.",
    ],
    tips: [
      "Persiapan untuk handstand push-up. Bagus untuk bentuk bahu bulat.",
      "Posisi kaki bisa lebih dekat ke tangan untuk versi lebih sulit.",
    ],
    videoEmbedId: "paCOGgmLCA0",
    prMetric: "reps",
  },
  {
    id: "tricep-dip-chair",
    nama: "Tricep Dip (Kursi)",
    kategori: ["tricep", "lengan"],
    alat: ["kursi / meja"],
    deskripsi:
      "Latihan tricep menggunakan kursi atau sofa yang stabil.",
    langkah: [
      "PERSIAPAN: Pilih kursi/sofa yang STABIL (tidak beroda, tidak goyang). Taruh dengan sandaran menempel tembok untuk keamanan.",
      "POSISI AWAL: Duduk di pinggir kursi. Taruh kedua telapak tangan di sisi pinggul, jari-jari menggenggam pinggir kursi.",
      "Geser pinggul ke depan sehingga bokong lepas dari kursi. Kaki ditekuk 90° (pemula) atau lurus ke depan (lebih berat).",
      "Lengan lurus menopang badan. Dada terbuka, bahu ditarik ke belakang & ke bawah.",
      "TURUN: Tarik napas. Tekuk siku ke BELAKANG (bukan ke samping), turunkan badan.",
      "Turunkan sampai lengan atas sejajar dengan lantai, atau sampai terasa regangan di tricep. Jangan turun terlalu dalam — berbahaya untuk bahu.",
      "Jeda 1 detik di posisi bawah.",
      "NAIK: Buang napas, tekan kursi dengan telapak tangan. Luruskan lengan dengan kekuatan tricep.",
      "Jangan menggunakan kaki untuk membantu mendorong — biarkan tricep yang bekerja.",
      "Ulangi dengan tempo terkontrol.",
      "SELESAI: Dorong ke atas, lalu duduk kembali di kursi.",
    ],
    kesalahanUmum: [
      "Siku terbuka ke samping — Solusi: tekan siku ke belakang, dekat badan.",
      "Bahu terangkat ke kuping — Solusi: tarik bahu ke bawah & ke belakang sepanjang gerakan.",
      "Turun terlalu dalam — bahaya rotator cuff. Solusi: stop saat lengan atas sejajar lantai.",
      "Kaki membantu mendorong — Solusi: pindahkan kaki lebih jauh ke depan.",
    ],
    tips: [
      "Pastikan kursi stabil dan tidak beroda.",
      "Tekuk lutut untuk versi lebih ringan, lurus untuk lebih berat.",
    ],
    videoEmbedId: "6kALZikXxLc",
    prMetric: "reps",
    alternatifTanpaAlat: {
      nama: "Floor Tricep Extension (Bodyweight Skull Crusher)",
      deskripsi: "Latihan tricep di lantai tanpa alat apapun — sama efektifnya dengan tricep dip.",
      langkah: [
        "POSISI AWAL: Posisi push-up, tapi tangan agak lebih maju ke depan dari bahu.",
        "TURUN: Tekuk SIKU saja (bukan bahu), turunkan lengan bawah ke lantai. Siku mengarah ke depan.",
        "Lengan atas tetap diam — hanya lengan bawah yang bergerak turun sampai menyentuh lantai.",
        "NAIK: Tekan dengan tricep, luruskan siku kembali ke posisi awal.",
        "Semakin jauh tangan dari bahu = semakin mudah. Geser tangan lebih dekat untuk lebih berat.",
      ],
      videoEmbedId: "fTQ5SSBi0FU",
    },
  },
  {
    id: "bicep-curl-botol",
    nama: "Bicep Curl (Botol Air / Dumbbell)",
    kategori: ["bisep", "lengan"],
    alat: ["botol air / dumbbell"],
    deskripsi:
      "Latihan bisep paling klasik. Pakai botol air 1.5L isi pasir/air, atau dumbbell.",
    langkah: [
      "PERSIAPAN: Pilih beban yang sesuai. Pemula: botol air 1.5L isi air (1.5 kg). Menengah: isi pasir basah (~3 kg) atau dumbbell 3-5 kg.",
      "POSISI AWAL: Berdiri tegak, kaki selebar bahu. Pegang botol/dumbbell di kedua tangan dengan telapak menghadap ke depan (supinated grip).",
      "Lengan menggantung lurus di samping tubuh. Siku menempel dekat ke sisi badan — ini penting.",
      "Tarik bahu ke belakang & ke bawah. Dada terbuka. Tatapan ke depan.",
      "ANGKAT: Buang napas. Tekuk siku, angkat beban ke arah bahu. HANYA lengan bawah yang bergerak — lengan atas tetap diam menempel badan.",
      "Angkat sampai beban hampir menyentuh bahu. Rasakan kontraksi penuh di bisep (peras otot di posisi atas).",
      "Tahan kontraksi 1-2 detik di posisi atas.",
      "TURUN: Tarik napas, turunkan beban PERLAHAN ke posisi awal (3 detik turun). Jangan dijatuhkan begitu saja — turun pelan = otot bekerja 2x lipat.",
      "Luruskan lengan sepenuhnya di posisi bawah sebelum mengulang.",
      "SELESAI: Letakkan beban dengan hati-hati setelah set selesai.",
    ],
    kesalahanUmum: [
      "Mengayun tubuh — pakai momentum bukan otot. Solusi: berdiri punggung menempel tembok.",
      "Siku bergerak ke depan saat mengangkat — Solusi: kunci siku di sisi badan sepanjang gerakan.",
      "Turun terlalu cepat — kehilangan separuh latihan. Solusi: hitung 3 detik saat menurunkan.",
      "Beban terlalu berat — form hancur. Solusi: turunkan beban, perfeksikan form.",
    ],
    tips: [
      "Gerakan harus pelan & terkontrol — jangan pakai momentum.",
      "Belum punya dumbbell? Isi botol 1.5L dengan pasir basah (~3kg) atau air (~1.5kg).",
      "Pertimbangkan beli dumbbell adjustable 2.5-10kg untuk progres jangka panjang.",
    ],
    videoUrl: "https://www.youtube.com/results?search_query=bicep+curl+dumbbell+form",
    videoEmbedId: "ykJmrZ5v0Oo",
    prMetric: "reps",
  },
  {
    id: "hammer-curl",
    nama: "Hammer Curl",
    kategori: ["bisep", "lengan"],
    alat: ["botol air / dumbbell"],
    deskripsi:
      "Variasi bicep curl dengan telapak tangan menghadap ke dalam (seperti pegang palu). Lebih fokus ke brachialis & lengan bawah.",
    langkah: [
      "POSISI AWAL: Berdiri tegak, kaki selebar bahu. Pegang dumbbell/botol di kedua tangan.",
      "Telapak tangan menghadap ke DALAM (saling berhadapan) — seperti memegang palu. Inilah perbedaan utama dengan bicep curl biasa.",
      "Lengan lurus di samping badan, siku dekat sisi tubuh.",
      "Dada terbuka, bahu ke belakang & ke bawah.",
      "ANGKAT: Buang napas, tekuk siku. Angkat beban ke bahu TANPA memutar pergelangan tangan — telapak tetap menghadap ke dalam.",
      "Angkat sampai beban sejajar bahu. Tahan & peras 1-2 detik.",
      "TURUN: Tarik napas, turunkan perlahan selama 3 detik ke posisi awal.",
      "Pastikan siku tidak bergerak ke depan — hanya lengan bawah yang bergerak.",
      "Bisa dilakukan bersamaan (kedua tangan naik bareng) atau bergantian (alternating).",
      "SELESAI: Letakkan beban perlahan setelah set selesai.",
    ],
    kesalahanUmum: [
      "Pergelangan tangan memutar — berubah jadi bicep curl biasa. Solusi: kunci posisi 'palu'.",
      "Siku ikut bergerak ke depan — Solusi: kunci siku di sisi badan.",
      "Tubuh mengayun — Solusi: berdiri menempel tembok atau duduk di kursi.",
    ],
    tips: [
      "Bagus untuk bikin lengan terlihat lebih tebal/penuh.",
      "Boleh selang-seling dengan bicep curl biasa.",
    ],
    videoEmbedId: "TwD-YGVP4Bk",
    prMetric: "reps",
  },
  {
    id: "inverted-row-meja",
    nama: "Inverted Row (Bawah Meja)",
    kategori: ["punggung", "bisep"],
    alat: ["kursi / meja"],
    deskripsi:
      "Pull-up versi mudah dengan meja kokoh. Bagus untuk melatih punggung & bisep.",
    langkah: [
      "PERSIAPAN: Cari meja yang KUAT dan stabil. Tes dulu: tekan meja dengan kuat — kalau goyang/geser, JANGAN dipakai. Meja makan kayu solid ideal.",
      "POSISI AWAL: Berbaring telentang di bawah meja. Pegang pinggir meja dengan tangan selebar bahu, grip overhand (telapak ke depan).",
      "Geser posisi sehingga dada tepat di bawah pinggir meja.",
      "Kaki lurus ke depan, tumit menumpu ke lantai. Tubuh lurus dari kepala sampai tumit (seperti plank terbalik).",
      "Kencangkan perut dan bokong. Bahu ditarik ke belakang.",
      "TARIK: Buang napas. Tarik tubuh ke atas dengan menarik siku ke belakang & menyatukan scapula (tulang belikat).",
      "Tarik sampai dada menyentuh atau hampir menyentuh pinggir meja.",
      "Peras otot punggung di posisi atas — bayangkan 'jepit pensil di antara tulang belikat'. Tahan 1-2 detik.",
      "TURUN: Tarik napas, turunkan tubuh perlahan (3 detik) sampai lengan lurus kembali.",
      "Jangan biarkan bahu jatuh ke depan di posisi bawah — jaga bahu tetap aktif.",
      "SELESAI: Lepaskan pegangan dan geser keluar dari bawah meja.",
    ],
    kesalahanUmum: [
      "Pinggul turun — Solusi: kencangkan core & bokong, jaga garis lurus.",
      "Hanya menarik dengan tangan, bukan punggung — Solusi: fokus tarik scapula ke belakang dulu, siku menyusul.",
      "Kepala mendongak — Solusi: pandangan ke langit-langit, leher netral.",
    ],
    tips: [
      "PASTIKAN MEJA KUAT — coba dulu dengan beban setengah badan sebelum full.",
      "Tekuk lutut untuk versi lebih ringan.",
      "Alternatif: pakai gagang sapu di antara 2 kursi yang stabil.",
    ],
    videoUrl: "https://www.youtube.com/results?search_query=inverted+row+at+home+table",
    videoEmbedId: "2Synad5Yo-g",
    prMetric: "reps",
    alternatifTanpaAlat: {
      nama: "Prone Y-T-W Raise (Telungkup di Lantai)",
      deskripsi: "Latihan punggung & bahu di lantai tanpa alat. Melatih otot yang sama dengan inverted row.",
      langkah: [
        "POSISI: Telungkup di lantai, dahi di handuk/bantal kecil. Lengan lurus di samping.",
        "Y-RAISE: Angkat kedua tangan ke atas membentuk huruf Y (jempol ke atas). Tahan 2 detik, turunkan.",
        "T-RAISE: Angkat kedua tangan ke samping membentuk huruf T. Tahan 2 detik, turunkan.",
        "W-RAISE: Tekuk siku 90°, angkat membentuk huruf W. Peras scapula. Tahan 2 detik, turunkan.",
        "Lakukan 8-12 rep per huruf. Fokus pada peras otot punggung, bukan kecepatan.",
      ],
      videoEmbedId: "QdGTI4Lshg4",
    },
  },
  {
    id: "resistance-band-row",
    nama: "Resistance Band Row",
    kategori: ["punggung", "bisep"],
    alat: ["resistance band"],
    deskripsi:
      "Latihan punggung dengan resistance band. Murah, ringkas, sangat efektif.",
    langkah: [
      "POSISI AWAL: Duduk di lantai dengan kaki lurus ke depan.",
      "Lingkarkan resistance band di telapak kaki (bagian tengah kaki, bukan jari).",
      "Pegang kedua ujung band dengan tangan. Duduk tegak, dada terbuka, bahu ke belakang.",
      "Tangan lurus ke depan — ini posisi awal. Band sudah sedikit tegang.",
      "TARIK: Buang napas. Tarik band ke arah perut bagian bawah (sekitar pusar).",
      "Tarik dengan siku mengarah ke belakang, dekat badan. Bayangkan menyikut orang di belakang.",
      "Peras scapula (tulang belikat) di akhir gerakan. Tahan 1-2 detik.",
      "LEPAS: Tarik napas, lepaskan perlahan ke posisi awal (3 detik). Jangan biarkan band 'menarik' tangan — kontrol penuh.",
      "Jaga punggung tetap tegak sepanjang gerakan — jangan condong ke belakang.",
      "SELESAI: Lepaskan band dari kaki setelah set selesai.",
    ],
    kesalahanUmum: [
      "Punggung membungkuk — Solusi: duduk tegak, dada keluar.",
      "Menarik ke atas (ke dada) bukan ke perut — Solusi: target tangan ke pusar.",
      "Bahu terangkat — Solusi: tarik bahu ke bawah sebelum mulai menarik.",
    ],
    tips: [
      "Resistance band loop set (~50-150 ribu) adalah investasi murah & multifungsi.",
      "Bisa juga lakukan berdiri dengan band diikat ke gagang pintu.",
    ],
    videoEmbedId: "xQNrFHEMhI4",
    prMetric: "reps",
  },
  {
    id: "plank",
    nama: "Plank",
    kategori: ["perut", "fullbody"],
    alat: ["tanpa alat", "matras"],
    deskripsi:
      "Latihan inti perut paling efektif. Membentuk perut & juga melatih bahu, punggung.",
    langkah: [
      "POSISI AWAL: Berlutut di matras, letakkan kedua siku/lengan bawah di lantai. Siku tepat di bawah bahu.",
      "Langkahkan kaki ke belakang satu per satu sampai tubuh lurus. Jari kaki sebagai tumpuan.",
      "Tubuh membentuk garis lurus dari kepala sampai tumit — cek di cermin jika bisa.",
      "Kencangkan perut (bayangkan perut ditarik ke tulang belakang), kencangkan bokong, dan kencangkan paha.",
      "Lengan bawah sejajar (atau tangan bisa disatukan — pilih yang nyaman).",
      "TAHAN: Bernapas normal — jangan menahan napas! Napas pendek teratur: hirup 2 detik, hembuskan 2 detik.",
      "Pandangan ke lantai sekitar 30 cm di depan tangan. Leher netral — jangan menunduk atau mendongak.",
      "Fokus terus kencangkan perut & bokong. Kalau pinggul mulai turun, inilah saatnya berhenti.",
      "Tahan selama target waktu (pemula 20 detik, naikkan 5 detik per minggu).",
      "SELESAI: Turunkan lutut ke lantai PERLAHAN. Jangan langsung collapse. Istirahat di posisi child's pose.",
    ],
    kesalahanUmum: [
      "Pinggul turun (membentuk U) — paling bahaya untuk punggung bawah. Solusi: kencangkan core & bokong.",
      "Pinggul naik (membentuk A) — lebih ringan tapi kurang efektif. Solusi: turunkan pinggul sedikit.",
      "Menahan napas — bikin pusing. Solusi: bernapas teratur!",
      "Bahu naik ke kuping — Solusi: tekan siku ke lantai, tarik bahu ke bawah.",
    ],
    tips: [
      "Pemula: mulai 20 detik, naikkan 5 detik tiap minggu.",
      "Target: 60 detik dalam 4 minggu.",
      "Lebih baik plank 30 detik dengan bentuk sempurna daripada 2 menit pinggul turun.",
    ],
    videoUrl: "https://www.youtube.com/results?search_query=plank+benar+pemula",
    videoEmbedId: "pSHjTRCQxIw",
    prMetric: "durasi-detik",
  },
  {
    id: "side-plank",
    nama: "Side Plank",
    kategori: ["perut"],
    alat: ["tanpa alat", "matras"],
    deskripsi:
      "Plank menyamping. Fokus ke perut samping (oblique).",
    langkah: [
      "POSISI AWAL: Berbaring miring ke satu sisi di matras.",
      "Taruh siku di lantai tepat di bawah bahu. Lengan bawah lurus ke depan.",
      "Kaki bisa ditumpuk (lebih sulit) atau kaki atas di depan bawah (lebih stabil).",
      "ANGKAT: Angkat pinggul dari lantai sehingga tubuh membentuk garis lurus dari kepala sampai kaki.",
      "Tangan atas bisa di pinggul, lurus ke langit-langit, atau di belakang kepala.",
      "TAHAN: Kencangkan perut samping (oblique). Bernapas teratur.",
      "Jaga pinggul tetap tinggi — jangan biarkan melorot. Kalau pinggul mulai turun, saatnya berhenti.",
      "Tahan selama target waktu.",
      "GANTI SISI: Turunkan pinggul perlahan, putar badan, ulangi di sisi lainnya.",
      "SELESAI: Pastikan kedua sisi mendapat waktu yang sama.",
    ],
    kesalahanUmum: [
      "Pinggul jatuh ke depan atau belakang — Solusi: bayangkan badan menempel di dinding.",
      "Siku tidak di bawah bahu — Solusi: cek posisi siku sebelum angkat.",
      "Menahan napas — Solusi: bernapas normal!",
    ],
    tips: [
      "Pemula bisa tekuk lutut bawah untuk versi lebih ringan.",
      "Versi sulit: angkat kaki atas atau angkat tangan atas ke langit-langit.",
    ],
    videoEmbedId: "K2VljzCC16g",
    prMetric: "durasi-detik",
  },
  {
    id: "crunch",
    nama: "Crunch",
    kategori: ["perut"],
    alat: ["matras"],
    deskripsi: "Crunch untuk perut bagian atas (six-pack area).",
    langkah: [
      "POSISI AWAL: Berbaring telentang di matras. Lutut ditekuk ~90°, telapak kaki rata di lantai.",
      "Taruh tangan di belakang kepala dengan jari menyentuh ringan (JANGAN menggenggam atau menarik kepala).",
      "Alternatif tangan: silangkan di dada atau lurus di samping tubuh (lebih mudah).",
      "Punggung bawah menempel ke lantai. Ini penting.",
      "ANGKAT: Buang napas KUAT. Angkat bahu dan punggung atas dari lantai dengan mengencangkan perut atas.",
      "Bayangkan 'menarik tulang rusuk ke arah panggul'. Gerakan hanya ~30° — bahu terangkat 10-15 cm.",
      "Punggung bawah TETAP menempel lantai — hanya bahu & punggung atas yang terangkat.",
      "Tahan kontraksi 1-2 detik di posisi atas. Rasakan perut atas mengencang.",
      "TURUN: Tarik napas, turunkan bahu PERLAHAN ke lantai. Jangan biarkan kepala/bahu menyentuh lantai sepenuhnya sampai set selesai (jaga tegangan).",
      "Ulangi dengan tempo terkontrol.",
      "SELESAI: Setelah set selesai, turunkan kepala sepenuhnya dan rilekskan.",
    ],
    kesalahanUmum: [
      "Menarik leher dengan tangan — bisa cedera leher. Solusi: jari hanya menyentuh ringan di belakang kepala.",
      "Mengangkat terlalu tinggi (duduk penuh) — jadi sit-up, bukan crunch. Solusi: hanya bahu & punggung atas.",
      "Punggung bawah terangkat — Solusi: tekan punggung bawah ke lantai sepanjang gerakan.",
    ],
    tips: [
      "Jangan tarik leher dengan tangan — itu cuma bikin leher sakit.",
      "Fokus 'menarik tulang rusuk ke arah panggul'.",
    ],
    videoEmbedId: "Xyd_fa5zoEU",
    prMetric: "reps",
  },
  {
    id: "bicycle-crunch",
    nama: "Bicycle Crunch",
    kategori: ["perut"],
    alat: ["matras"],
    deskripsi: "Variasi crunch dengan gerakan menyilang. Melatih perut atas & samping sekaligus.",
    langkah: [
      "POSISI AWAL: Berbaring telentang di matras. Tangan di belakang kepala (jari menyentuh ringan, jangan tarik).",
      "Angkat kedua kaki — lutut ditekuk 90° (paha tegak lurus lantai, betis sejajar lantai).",
      "Angkat bahu sedikit dari lantai — posisi crunch ringan.",
      "GERAKAN: Buang napas. Putar tubuh — bawa siku KANAN ke arah lutut KIRI.",
      "Bersamaan, luruskan kaki kanan ke depan (jangan sampai menyentuh lantai).",
      "Tarik napas kembali ke tengah (1 detik).",
      "Putar ke sisi lain — siku KIRI ke lutut KANAN, luruskan kaki kiri.",
      "Gerakan seperti mengayuh sepeda — bergantian kanan-kiri secara terkontrol.",
      "Setiap putaran kanan-kiri = 1 rep.",
      "SELESAI: Setelah semua rep, turunkan kaki dan bahu perlahan.",
    ],
    kesalahanUmum: [
      "Gerakan terlalu cepat — kehilangan kontraksi. Solusi: tempo pelan 2 detik per sisi.",
      "Hanya siku yang bergerak, bukan batang tubuh — Solusi: putar dari tulang rusuk, bukan cuma geser siku.",
      "Kaki menyentuh lantai — Solusi: jaga kaki mengambang sepanjang set.",
    ],
    tips: [
      "Gerakan harus terkontrol, bukan cepat-cepat.",
      "Putar dari batang tubuh, bukan cuma siku.",
    ],
    videoEmbedId: "9FGilxCbdz8",
    prMetric: "reps",
  },
  {
    id: "leg-raise",
    nama: "Leg Raise",
    kategori: ["perut"],
    alat: ["matras"],
    deskripsi: "Latihan perut bagian bawah — area paling sulit dilatih.",
    langkah: [
      "POSISI AWAL: Berbaring telentang di matras. Kaki lurus, rapat.",
      "Taruh tangan di samping tubuh dengan telapak menempel lantai, atau di bawah pantat untuk support punggung bawah.",
      "Punggung bawah ditekan ke lantai — ini SANGAT penting untuk menghindari sakit punggung.",
      "ANGKAT: Buang napas. Angkat kedua kaki BERSAMAAN ke atas dengan kaki tetap lurus dan rapat.",
      "Angkat sampai kaki tegak lurus (90°) dengan lantai.",
      "Jaga punggung bawah tetap menempel lantai sepanjang gerakan.",
      "Tahan 1 detik di posisi atas.",
      "TURUN: Tarik napas. Turunkan kaki PERLAHAN (3-4 detik) ke arah lantai.",
      "Stop sekitar 10-15 cm dari lantai — JANGAN biarkan kaki menyentuh lantai sampai set selesai.",
      "Rasakan perut bawah bekerja keras menahan kaki.",
      "SELESAI: Di rep terakhir, turunkan kaki sampai lantai dengan terkontrol.",
    ],
    kesalahanUmum: [
      "Punggung bawah terangkat — sangat bahaya. Solusi: taruh tangan di bawah pantat, tekan punggung ke lantai.",
      "Kaki turun terlalu cepat — Solusi: hitung 3-4 detik saat menurunkan.",
      "Tekuk lutut saat capek — Solusi: boleh sedikit bengkok, tapi jaga konsisten.",
    ],
    tips: [
      "Tekuk lutut sedikit kalau punggung bawah sakit.",
      "Pemula: angkat satu kaki bergantian dulu.",
    ],
    videoEmbedId: "JB2oyawG9KI",
    prMetric: "reps",
  },
  {
    id: "mountain-climber",
    nama: "Mountain Climber",
    kategori: ["perut", "kardio", "fullbody"],
    alat: ["matras"],
    deskripsi:
      "Latihan kardio + perut sekaligus. Bagus untuk membakar lemak.",
    langkah: [
      "POSISI AWAL: Mulai di posisi push-up — tangan lurus di bawah bahu, tubuh lurus dari kepala ke tumit.",
      "Kencangkan perut dan bokong. Berat terbagi rata di tangan dan kaki.",
      "GERAKAN: Angkat kaki kanan dari lantai, tarik lutut kanan ke arah dada dengan cepat.",
      "Saat kaki kanan kembali ke belakang, langsung tarik kaki kiri ke dada.",
      "Bergantian seperti 'lari di tempat' dalam posisi plank.",
      "Tempo LAMBAT (fokus core): 1 detik per kaki, kontrol penuh.",
      "Tempo CEPAT (kardio HIIT): secepat mungkin sambil jaga form.",
      "Bernapas cepat dan teratur — jangan menahan napas.",
      "Jaga pinggul tetap rendah dan stabil — jangan naik turun.",
      "SELESAI: Setelah waktu habis, tahan di posisi plank 2 detik, lalu turunkan lutut.",
    ],
    kesalahanUmum: [
      "Pinggul naik tinggi — jadi mountain humper, bukan climber. Solusi: jaga pinggul sejajar bahu.",
      "Tangan bergeser ke depan — Solusi: tangan tetap di bawah bahu.",
      "Lutut tidak sampai ke dada — Solusi: tarik lebih kuat, atau pelan tempo.",
    ],
    tips: [
      "Tempo bisa lambat (fokus core) atau cepat (kardio HIIT).",
      "Biasanya 30-45 detik per set sudah cukup membakar.",
    ],
    videoEmbedId: "nmwgirgXLYM",
    prMetric: "durasi-detik",
  },
  {
    id: "russian-twist",
    nama: "Russian Twist",
    kategori: ["perut"],
    alat: ["matras", "botol air / dumbbell"],
    deskripsi: "Melatih perut samping (oblique) dengan gerakan putar.",
    langkah: [
      "POSISI AWAL: Duduk di matras, lutut ditekuk ~90°, telapak kaki di lantai.",
      "Condongkan tubuh ke belakang sekitar 45° — punggung lurus, dada terbuka.",
      "Pemula: kaki tetap di lantai. Level lanjut: angkat kaki sedikit dari lantai.",
      "Satukan kedua tangan di depan dada (atau pegang botol/beban).",
      "PUTAR: Buang napas, putar batang tubuh ke KANAN. Tangan ikut bergerak ke samping kanan.",
      "Putar dari tulang rusuk dan pinggang — bukan hanya menggeser tangan.",
      "Tahan 1 detik di sisi kanan.",
      "Tarik napas kembali ke tengah, lalu putar ke KIRI.",
      "Setiap putaran kanan-kiri = 1 rep.",
      "Jaga punggung tetap lurus (tidak membungkuk) sepanjang gerakan.",
      "SELESAI: Kembali ke posisi tengah, turunkan kaki, dan rilekskan.",
    ],
    kesalahanUmum: [
      "Hanya tangan yang bergerak, badan diam — Solusi: putar dari pinggang, bayangkan tulang rusuk ikut memutar.",
      "Punggung terlalu condong ke belakang — Solusi: 45° cukup, jangan lebih.",
      "Gerakan terlalu cepat — Solusi: tahan 1 detik di tiap sisi.",
    ],
    tips: [
      "Pemula bisa biarkan kaki di lantai dulu.",
      "Tambah beban (botol air) untuk progres.",
    ],
    videoEmbedId: "wkD8rjkodUI",
    prMetric: "reps",
  },
  {
    id: "squat",
    nama: "Bodyweight Squat",
    kategori: ["kaki", "fullbody"],
    alat: ["tanpa alat"],
    deskripsi:
      "Walaupun fokus kamu lengan & perut, latihan kaki PENTING untuk pembentukan tubuh & metabolisme.",
    langkah: [
      "POSISI AWAL: Berdiri tegak, kaki selebar bahu atau sedikit lebih lebar.",
      "Ujung kaki mengarah sedikit ke luar (~15-30°).",
      "Tangan bisa lurus ke depan (untuk keseimbangan), silangkan di dada, atau di belakang kepala.",
      "Dada terbuka, bahu ke belakang, pandangan ke depan.",
      "TURUN: Tarik napas DALAM. Dorong pinggul ke BELAKANG dulu (seperti mau duduk di kursi), baru tekuk lutut.",
      "Turunkan tubuh sampai paha SEJAJAR dengan lantai atau lebih rendah jika fleksibel.",
      "Lutut mengikuti arah ujung kaki — JANGAN biarkan lutut masuk ke dalam.",
      "Berat badan di tumit dan tengah kaki (bukan jari kaki). Tumit tidak boleh terangkat.",
      "Punggung tetap lurus/netral sepanjang gerakan — jangan membungkuk.",
      "NAIK: Buang napas KUAT. Dorong lantai melalui tumit, luruskan kaki kembali ke berdiri.",
      "Kencangkan bokong di posisi atas.",
      "SELESAI: Berdiri tegak penuh, lalu ulangi.",
    ],
    kesalahanUmum: [
      "Lutut masuk ke dalam (valgus) — bahaya ligamen. Solusi: dorong lutut keluar searah jari kaki.",
      "Tumit terangkat — Solusi: berat di tumit, atau taruh buku tipis di bawah tumit.",
      "Punggung membungkuk — Solusi: dada terbuka, pandangan ke depan, bukan ke bawah.",
      "Tidak turun cukup dalam — Solusi: minimal paha sejajar lantai (parallel).",
    ],
    tips: [
      "Lutut jangan masuk ke dalam — searah dengan ujung kaki.",
      "Punggung tetap netral, dada terbuka.",
      "Kaki yang kuat = metabolisme tinggi = lebih cepat bentuk badan.",
    ],
    videoEmbedId: "YaXPRqUwItQ",
    prMetric: "reps",
  },
  {
    id: "jumping-jack",
    nama: "Jumping Jack",
    kategori: ["kardio", "fullbody"],
    alat: ["tanpa alat"],
    deskripsi: "Pemanasan & kardio ringan, cocok di rumah.",
    langkah: [
      "POSISI AWAL: Berdiri tegak, kaki rapat, tangan di samping tubuh.",
      "LOMPAT BUKA: Lompat kecil sambil buka kaki selebar bahu.",
      "Bersamaan, angkat kedua tangan ke atas hingga hampir bertemu di atas kepala.",
      "Mendarat dengan lutut sedikit ditekuk untuk meredam benturan.",
      "LOMPAT TUTUP: Lompat kembali — kaki rapat, tangan turun ke samping.",
      "Gerakan harus berirama dan terkoordinasi — kaki dan tangan bergerak bersamaan.",
      "Bernapas teratur: hirup saat buka, hembuskan saat tutup.",
      "SELESAI: Setelah target waktu/rep, perlambat tempo lalu berhenti.",
    ],
    kesalahanUmum: [
      "Mendarat dengan kaki kaku/lurus — Solusi: tekuk lutut sedikit saat mendarat.",
      "Tangan tidak sampai atas — Solusi: angkat tangan penuh, hampir bertemu di atas kepala.",
    ],
    tips: ["Bagus untuk warm-up 1-2 menit sebelum latihan utama."],
    videoEmbedId: "c4DAnQ6DtF8",
  },
  {
    id: "high-knees",
    nama: "High Knees",
    kategori: ["kardio"],
    alat: ["tanpa alat"],
    deskripsi: "Kardio intensitas tinggi untuk membakar lemak.",
    langkah: [
      "POSISI AWAL: Berdiri tegak, kaki selebar pinggul. Tangan di samping, siku ditekuk 90°.",
      "GERAKAN: Angkat lutut KANAN setinggi pinggul (paha sejajar lantai) dengan cepat.",
      "Saat kaki kanan turun, langsung angkat lutut KIRI.",
      "Bergantian secepat mungkin — seperti lari di tempat tapi lutut TINGGI.",
      "Ayunkan tangan seperti lari biasa — tangan kanan maju saat lutut kiri naik, dan sebaliknya.",
      "Mendarat di ujung kaki (ball of foot), bukan tumit.",
      "Jaga postur tegak — jangan condong ke belakang.",
      "SELESAI: Perlambat tempo, lalu berjalan di tempat untuk cool down.",
    ],
    kesalahanUmum: [
      "Lutut tidak cukup tinggi — Solusi: target lutut setinggi pinggul atau lebih.",
      "Badan condong ke belakang — Solusi: condong sedikit ke depan.",
      "Mendarat dengan tumit — Solusi: mendarat di ujung kaki.",
    ],
    tips: ["Untuk HIIT, lakukan 30 detik all-out, istirahat 30 detik, ulangi 4-6x."],
    videoEmbedId: "OAJ_J3EZkdY",
  },
  {
    id: "burpee",
    nama: "Burpee",
    kategori: ["kardio", "fullbody"],
    alat: ["matras"],
    deskripsi:
      "Latihan paling brutal untuk fat-burn. Melatih hampir seluruh otot tubuh.",
    langkah: [
      "POSISI AWAL: Berdiri tegak, kaki selebar bahu.",
      "JONGKOK: Tekuk lutut, jongkok, taruh kedua telapak tangan di lantai di depan kaki.",
      "LOMPAT KE PLANK: Lompat kedua kaki ke belakang sekaligus ke posisi plank. Tubuh lurus.",
      "PUSH-UP (opsional): Lakukan 1 push-up di posisi plank. Pemula boleh skip ini.",
      "LOMPAT KE DEPAN: Lompat kedua kaki ke depan — kaki mendarat di samping tangan.",
      "LOMPAT KE ATAS: Dari posisi jongkok, lompat setinggi mungkin ke atas. Angkat tangan ke atas saat lompat.",
      "MENDARAT: Mendarat dengan lutut sedikit ditekuk, langsung masuk ke rep berikutnya.",
      "Bernapas: buang napas saat lompat ke atas, tarik napas di posisi plank.",
      "SELESAI: Setelah semua rep, berdiri dan istirahat. Napas akan sangat cepat — itu normal.",
    ],
    kesalahanUmum: [
      "Punggung melengkung di posisi plank — Solusi: kencangkan core saat lompat ke belakang.",
      "Lompatan pendek — Solusi: lompat setinggi mungkin, angkat tangan.",
      "Form hancur karena capek — Solusi: pelan tempo tapi jaga form, atau versi pemula (step-out).",
    ],
    tips: [
      "Pemula: skip push-up & lompatan, cukup step out + step in.",
      "Burpee adalah salah satu latihan fat-burning paling efisien.",
    ],
    videoEmbedId: "qLBImHhCXSw",
    prMetric: "reps",
  },
  {
    id: "walk-stretch",
    nama: "Jalan + Stretching",
    kategori: ["kardio"],
    alat: ["tanpa alat"],
    deskripsi:
      "Aktivitas pemulihan untuk hari istirahat. Bantu sirkulasi & mencegah otot kaku.",
    langkah: [
      "JALAN KAKI (20-30 menit): Jalan dengan tempo santai di sekitar rumah, kompleks, atau di treadmill.",
      "Jangan terlalu cepat — ini recovery, bukan kardio. Kamu harus bisa ngobrol sambil jalan.",
      "STRETCHING (10 menit setelah jalan):",
      "Leher: miringkan kepala ke kanan 30 detik, ke kiri 30 detik. Putar pelan 5x per arah.",
      "Bahu: angkat bahu ke kuping, tahan 5 detik, lepas. Ulangi 5x.",
      "Dada: tangan di kusen pintu, putar badan menjauhi tangan. 30 detik per sisi.",
      "Hip flexor: posisi lunge, tekan pinggul ke depan. 30 detik per sisi.",
      "Hamstring: berdiri, angkat 1 kaki ke kursi, condong ke depan. 30 detik per kaki.",
      "Quadricep: berdiri 1 kaki, tarik kaki belakang ke bokong. 30 detik per kaki.",
      "SELESAI: Tarik napas dalam 5x (4 detik hirup, 4 detik tahan, 4 detik hembuskan).",
    ],
    tips: [
      "Hari istirahat bukan berarti rebahan total — gerakan ringan justru bantu recovery.",
      "Stretching bahu, leher, hip flexor, hamstring penting kalau sering duduk.",
    ],
    videoEmbedId: "c4DAnQ6DtF8",
  },
  // ====== ADVANCED EXERCISES (Week 5-24) ======
  {
    id: "decline-push-up",
    nama: "Decline Push-up (Kaki di Kursi)",
    kategori: ["dada", "bahu", "tricep"],
    alat: ["kursi / meja", "matras"],
    deskripsi:
      "Push-up dengan kaki diangkat ke kursi — beban lebih ke bahu & dada atas. Progres setelah push-up standar mudah.",
    langkah: [
      "PERSIAPAN: Taruh kursi/sofa stabil di belakang. Pastikan tidak bergeser.",
      "POSISI AWAL: Mulai dari posisi push-up, lalu angkat kaki satu per satu ke atas kursi.",
      "Tangan di lantai selebar bahu. Tubuh membentuk garis lurus diagonal dari kaki (atas) ke kepala.",
      "Kencangkan perut dan bokong ekstra — posisi ini lebih menantang keseimbangan.",
      "TURUN: Tarik napas. Tekuk siku, turunkan dada ke lantai. Siku ~45° dari badan.",
      "Turunkan sampai dahi atau hidung hampir menyentuh lantai.",
      "Jeda 1 detik.",
      "NAIK: Buang napas, dorong kembali ke posisi awal.",
      "Jaga tubuh tetap lurus — jangan biarkan pinggul naik atau turun.",
      "SELESAI: Turunkan kaki satu per satu dari kursi.",
    ],
    kesalahanUmum: [
      "Pinggul naik membentuk V — Solusi: kencangkan core, tubuh lurus diagonal.",
      "Kaki jatuh dari kursi — Solusi: taruh kaki lebih stabil, ujung jari kaki di tepi kursi.",
    ],
    tips: [
      "Semakin tinggi kursi = semakin berat ke bahu.",
      "Kuasai dulu 3x15 push-up standar sebelum naik ke decline.",
    ],
    videoEmbedId: "SKPab2YC8BE",
    prMetric: "reps",
    alternatifTanpaAlat: {
      nama: "Pike Push-up (Kaki di Lantai)",
      deskripsi: "Push-up dengan pinggul tinggi — menarget bahu & dada atas sama seperti decline, tanpa butuh kursi.",
      langkah: [
        "POSISI: Bentuk huruf V terbalik — tangan & kaki di lantai, pinggul tinggi ke atas.",
        "Kaki selebar bahu, tangan selebar bahu. Jaga kaki & lengan lurus.",
        "TURUN: Tekuk siku, turunkan kepala ke arah lantai di antara kedua tangan.",
        "NAIK: Dorong kembali ke posisi V. Semakin dekat kaki ke tangan = semakin berat.",
      ],
      videoEmbedId: "paCOGgmLCA0",
    },
  },
  {
    id: "archer-push-up",
    nama: "Archer Push-up",
    kategori: ["dada", "tricep"],
    alat: ["tanpa alat", "matras"],
    deskripsi:
      "Push-up satu sisi — beban hampir 70% ditahan 1 tangan. Progres ke one-arm push-up.",
    langkah: [
      "POSISI AWAL: Posisi push-up dengan tangan JAUH lebih lebar dari bahu (2x lebar bahu).",
      "Jari-jari kedua tangan mengarah ke samping (keluar).",
      "Tubuh lurus, core kencang.",
      "TURUN KE KANAN: Geser tubuh ke arah tangan kanan. Tekuk siku kanan.",
      "Tangan kiri tetap lurus — lengan kiri memanjang ke samping seperti memanah.",
      "Turunkan sampai dada hampir menyentuh tangan kanan.",
      "NAIK: Dorong dengan tangan kanan, kembali ke posisi tengah.",
      "TURUN KE KIRI: Ulangi ke sisi kiri — tekuk siku kiri, tangan kanan lurus.",
      "Kanan-kiri = 1 rep.",
      "SELESAI: Kembali ke tengah, turunkan lutut.",
    ],
    kesalahanUmum: [
      "Tangan yang lurus ikut menekuk — Solusi: kunci siku tangan yang memanjang.",
      "Jangkauan terlalu kecil — Solusi: perlebar tangan, turun lebih dalam ke satu sisi.",
    ],
    tips: [
      "Mulai dengan jangkauan kecil dulu, perlebar bertahap.",
      "Persiapan untuk one-arm push-up dalam 6-12 bulan.",
    ],
    videoEmbedId: "MxVbNel13Ek",
    prMetric: "reps",
  },
  {
    id: "weighted-row",
    nama: "Weighted Inverted Row",
    kategori: ["punggung", "bisep"],
    alat: ["kursi / meja"],
    deskripsi:
      "Inverted row dengan beban tambahan (tas isi buku di dada). Progres setelah row dengan body weight terlalu mudah.",
    langkah: [
      "PERSIAPAN: Isi backpack dengan buku/botol air (3-8 kg). Pakai di DEPAN badan (bukan di punggung).",
      "POSISI AWAL: Masuk ke posisi inverted row di bawah meja kokoh.",
      "Pegang pinggir meja selebar bahu. Tubuh lurus dari kepala ke tumit.",
      "Backpack ada di dada — ini menambah beban yang harus ditarik.",
      "TARIK: Buang napas. Tarik dada ke arah meja dengan menyatukan scapula.",
      "Tahan 1-2 detik di atas.",
      "TURUN: Turunkan perlahan 3 detik.",
      "SELESAI: Geser keluar dari meja, lepas backpack.",
    ],
    kesalahanUmum: [
      "Backpack melorot — Solusi: kencangkan strap, atau pegang dengan satu tangan di dada.",
      "Beban terlalu berat, form hancur — Solusi: kurangi isi tas sampai bisa 8 rep bersih.",
    ],
    tips: [
      "Naikkan beban 1-2 kg setiap kali 3x12 rep terasa mudah.",
      "Jaga form — lebih baik kurang beban tapi gerakan full.",
    ],
    videoEmbedId: "hXTc1mDnZCw",
    prMetric: "reps",
    alternatifTanpaAlat: {
      nama: "Backpack Bent-over Row (Berdiri)",
      deskripsi: "Row dengan backpack berat tanpa butuh meja — berdiri membungkuk dan tarik tas.",
      langkah: [
        "PERSIAPAN: Isi backpack dengan buku/botol (5-15 kg). Pegang strap tas dengan kedua tangan.",
        "POSISI: Berdiri, kaki selebar bahu. Bungkuk ke depan ~45° dengan punggung LURUS.",
        "TARIK: Buang napas, tarik tas ke arah perut. Peras scapula di atas. Tahan 1 detik.",
        "TURUN: Tarik napas, turunkan pelan 2-3 detik.",
      ],
    },
  },
  {
    id: "negative-pull-up",
    nama: "Negative Pull-up",
    kategori: ["punggung", "bisep"],
    alat: ["tanpa alat"],
    deskripsi:
      "Lompat ke posisi atas pull-up, turun pelan-pelan (5+ detik). Cara paling cepat membangun pull-up.",
    langkah: [
      "PERSIAPAN: Berdiri di bawah pull-up bar (bar pintu / dahan kuat / pull-up bar DIY). Taruh kursi di bawah jika perlu untuk menjangkau bar.",
      "POSISI AWAL: Pegang bar dengan grip overhand (telapak ke depan) selebar bahu.",
      "NAIK: Lompat (atau step up dari kursi) sampai dagu BERADA DI ATAS bar. Dada dekat bar.",
      "Tarik bahu ke bawah (scapula aktif). Ini posisi awal turun.",
      "TURUN: Tarik napas. Turunkan tubuh SEPELAN MUNGKIN. Target: minimal 5 detik untuk turun dari atas ke bawah.",
      "Rasakan punggung dan bisep menahan berat badan selama turun.",
      "Turun sampai lengan lurus sepenuhnya.",
      "ULANGI: Lepaskan bar, kembali naik (lompat/step up), ulangi turun pelan.",
      "SELESAI: Setelah set selesai, step down dari kursi.",
    ],
    kesalahanUmum: [
      "Turun terlalu cepat (jatuh) — Solusi: konsentrasi penuh, target 5 detik minimum.",
      "Hanya turun setengah — Solusi: turun sampai lengan benar-benar lurus.",
      "Bahu naik ke kuping — Solusi: tarik scapula ke bawah sebelum mulai turun.",
    ],
    tips: [
      "5-8 negative per set sudah sangat berat.",
      "Setelah bisa 3x5 negative slow control, coba 1 pull-up murni.",
    ],
    videoEmbedId: "gbPURTSxQLY",
    prMetric: "reps",
  },
  {
    id: "pull-up",
    nama: "Pull-up",
    kategori: ["punggung", "bisep"],
    alat: ["tanpa alat"],
    deskripsi:
      "Raja semua latihan punggung atas. Butuh pull-up bar atau dahan.",
    langkah: [
      "POSISI AWAL: Gantung di bar dengan grip overhand (telapak ke depan) selebar bahu.",
      "Lengan lurus penuh. Kaki bisa disilangkan di belakang atau ditekuk.",
      "Tarik bahu ke bawah (aktifkan scapula) — bahu jangan menempel kuping.",
      "TARIK: Buang napas. Tarik tubuh ke atas — inisiatif dari punggung (lats), bukan hanya tangan.",
      "Bayangkan 'menarik siku ke saku celana' — ini membantu mengaktifkan punggung.",
      "Tarik sampai dagu MELEWATI bar. Dada hampir menyentuh bar.",
      "Peras otot punggung di atas. Tahan 1 detik.",
      "TURUN: Tarik napas, turunkan tubuh terkontrol (3 detik) sampai lengan lurus penuh.",
      "Jangan 'jatuh' ke bawah — kontrol penuh.",
      "SELESAI: Lepaskan bar setelah set selesai. Shake out lengan.",
    ],
    kesalahanUmum: [
      "Kipping (mengayun tubuh) — Solusi: jaga tubuh stabil, gerak hanya naik-turun.",
      "Dagu tidak melewati bar — Solusi: tarik lebih tinggi atau lakukan negative pull-up dulu.",
      "Bahu naik ke kuping — Solusi: scapula ke bawah sebelum mulai menarik.",
    ],
    tips: [
      "Bahu jangan naik ke kuping — tahan scapula ke bawah.",
      "Belum bisa 1? Lakukan negative pull-up dulu.",
    ],
    videoEmbedId: "eGo4IYlbE5g",
    prMetric: "reps",
  },
  {
    id: "chin-up",
    nama: "Chin-up",
    kategori: ["bisep", "punggung"],
    alat: ["tanpa alat"],
    deskripsi:
      "Pull-up dengan grip underhand (telapak menghadap kamu). Lebih banyak ke bisep.",
    langkah: [
      "POSISI AWAL: Gantung di bar dengan grip underhand (telapak menghadap KAMU) selebar bahu.",
      "Lengan lurus penuh. Tarik bahu ke bawah, aktifkan scapula.",
      "TARIK: Buang napas. Tarik tubuh ke atas — fokus pada kontraksi bisep dan punggung bawah.",
      "Tarik sampai dagu melewati bar.",
      "Peras bisep dan punggung di atas. Tahan 1 detik.",
      "TURUN: Turunkan terkontrol 3 detik sampai lengan lurus.",
      "SELESAI: Lepas bar, istirahat.",
    ],
    kesalahanUmum: [
      "Mengayun (kipping) — Solusi: silangkan kaki di belakang, core kencang.",
      "Half rep (dagu tidak sampai atas) — Solusi: turunkan rep tapi full range.",
    ],
    tips: [
      "Biasanya lebih mudah dari pull-up karena bisep ikut bantu.",
      "Goal sederhana: 5 chin-up murni di bulan ke-4.",
    ],
    videoEmbedId: "brhRXlOhsAM",
    prMetric: "reps",
  },
  {
    id: "hollow-hold",
    nama: "Hollow Body Hold",
    kategori: ["perut"],
    alat: ["matras"],
    deskripsi:
      "Standar gimnastik untuk core. Bikin perut & lower abs sangat kuat.",
    langkah: [
      "POSISI AWAL: Tiduran terlentang di matras. Punggung bawah ditekan ke lantai.",
      "Angkat kedua kaki lurus sekitar 15-30 cm dari lantai.",
      "Angkat kepala & bahu sedikit. Tangan lurus di atas kepala (sejajar telinga).",
      "TAHAN: Tubuh membentuk seperti 'pisang terbalik' — sedikit melengkung.",
      "Punggung bawah HARUS tetap menempel lantai. Ini kunci keamanan.",
      "Kencangkan semua otot: perut, paha, bokong, lengan.",
      "Bernapas teratur — jangan menahan napas.",
      "Tahan selama target waktu.",
      "SELESAI: Turunkan kaki dan tangan perlahan, rilekskan.",
    ],
    kesalahanUmum: [
      "Punggung bawah terangkat — sangat bahaya. Solusi: angkat kaki lebih tinggi atau tekuk lutut.",
      "Menahan napas — Solusi: napas pendek teratur.",
    ],
    tips: [
      "Pemula: tekuk lutut & taruh tangan di samping.",
      "Goal: 60 detik hold di bulan ke-3.",
    ],
    videoEmbedId: "LlDNef_Ztsc",
    prMetric: "durasi-detik",
  },
  {
    id: "l-sit-progression",
    nama: "L-Sit Progression",
    kategori: ["perut", "lengan"],
    alat: ["matras"],
    deskripsi:
      "Tahan tubuh di atas tangan dengan kaki lurus di depan. Latihan core paling brutal yang ada.",
    langkah: [
      "POSISI AWAL: Duduk di lantai, kaki lurus ke depan.",
      "Taruh kedua telapak tangan di lantai di samping pinggul. Jari-jari menghadap ke depan.",
      "ANGKAT (Tuck L-Sit — pemula): Dorong tangan ke lantai, angkat pinggul dari lantai.",
      "Tekuk lutut ke dada (tuck position). Tahan.",
      "ANGKAT (Full L-Sit — lanjutan): Sama seperti di atas, tapi kaki lurus ke depan, sejajar lantai.",
      "Kencangkan perut, hip flexor, dan tricep.",
      "TAHAN: Bernapas teratur. Tahan selama target waktu.",
      "SELESAI: Turunkan pinggul perlahan ke lantai.",
    ],
    kesalahanUmum: [
      "Tidak bisa angkat pinggul — Solusi: perkuat tricep dulu, atau gunakan parallette/buku sebagai tumpuan lebih tinggi.",
      "Kaki turun — Solusi: mulai dari tuck (lutut ditekuk), progres ke kaki lurus.",
    ],
    tips: [
      "5 detik hold sudah keras. Progres pelan-pelan.",
      "Bisa pakai dua kursi sebagai parallette.",
    ],
    videoEmbedId: "IUZJoSP66HI",
    prMetric: "durasi-detik",
  },
  {
    id: "wall-handstand-hold",
    nama: "Wall Handstand Hold",
    kategori: ["bahu", "lengan"],
    alat: ["tanpa alat"],
    deskripsi:
      "Handstand bersandar tembok. Bangun kekuatan & kepercayaan diri untuk handstand bebas.",
    langkah: [
      "PERSIAPAN: Cari tembok kosong. Taruh matras/bantal di bawah untuk keamanan kepala.",
      "CARA NAIK (Face-to-wall — lebih aman untuk pemula): Mulai posisi push-up dengan kaki dekat tembok.",
      "Jalan kaki NAIK ke atas tembok sambil geser tangan mundur mendekati tembok.",
      "CARA NAIK (Kick-up — lebih cepat): Berdiri menghadap menjauhi tembok, tangan di lantai, tendang kaki ke atas ke tembok.",
      "TAHAN: Posisi handstand dengan kaki bersandar tembok. Lengan lurus.",
      "Kencangkan core, bokong, dan kaki. Pandangan ke tangan (leher netral).",
      "Bernapas teratur.",
      "Tahan selama target waktu.",
      "TURUN: Jalan kaki turun perlahan di tembok, atau turunkan satu kaki lalu yang lain.",
      "SELESAI: Istirahat. Kocok pergelangan tangan jika perlu.",
    ],
    kesalahanUmum: [
      "Punggung melengkung (banana shape) — Solusi: kencangkan core & bokong, dorong bahu ke atas.",
      "Lengan bengkok — Solusi: kunci siku, dorong lantai aktif.",
    ],
    tips: [
      "Mulai 10-15 detik. Goal 60 detik di bulan ke-4.",
      "Latihan ini sangat bagus untuk bahu bulat & posture.",
    ],
    videoEmbedId: "2v1YDTzMcO8",
    prMetric: "durasi-detik",
  },
  {
    id: "pistol-squat-progression",
    nama: "Pistol Squat Progression",
    kategori: ["kaki"],
    alat: ["kursi / meja"],
    deskripsi:
      "Squat satu kaki. Cara paling efisien menguatkan kaki tanpa beban berat.",
    langkah: [
      "PERSIAPAN: Taruh kursi rendah di belakang untuk keamanan (box squat). Pegangan tembok di samping jika perlu.",
      "POSISI AWAL: Berdiri dengan satu kaki. Kaki lain lurus ke depan, terangkat dari lantai.",
      "Tangan lurus ke depan untuk keseimbangan.",
      "TURUN: Tarik napas. Tekuk lutut kaki yang berdiri — turunkan tubuh perlahan.",
      "Punggung tegak, dada terbuka. Kaki yang diangkat tetap lurus ke depan.",
      "Turunkan sampai pantat hampir menyentuh kursi (atau lantai untuk full pistol).",
      "NAIK: Buang napas. Dorong melalui tumit, kembali berdiri dengan satu kaki.",
      "Jaga keseimbangan — ini yang paling sulit.",
      "Selesaikan semua rep di satu kaki, baru pindah ke kaki lain.",
      "SELESAI: Berdiri dengan kedua kaki, istirahat.",
    ],
    kesalahanUmum: [
      "Jatuh ke belakang — Solusi: condong sedikit ke depan, tangan lurus ke depan.",
      "Lutut masuk ke dalam — Solusi: dorong lutut keluar searah jari kaki.",
      "Tidak bisa turun dalam — Solusi: mulai dari box squat (duduk di kursi, berdiri 1 kaki).",
    ],
    tips: [
      "Mulai dari box squat (jongkok di kursi rendah, berdiri 1 kaki).",
      "Goal: 5 pistol squat murni per kaki.",
    ],
    videoEmbedId: "vq5-vdgJc0I",
    prMetric: "reps",
    alternatifTanpaAlat: {
      nama: "Assisted Pistol Squat (Pegangan Tembok/Kusen Pintu)",
      deskripsi: "Pistol squat dengan pegangan tembok atau kusen pintu sebagai pengganti kursi.",
      langkah: [
        "Berdiri di samping tembok atau kusen pintu. Pegang dengan satu tangan.",
        "Angkat satu kaki lurus ke depan.",
        "TURUN: Jongkok dengan satu kaki, gunakan pegangan tembok untuk keseimbangan.",
        "Turunkan serendah mungkin. NAIK: Dorong ke atas dengan kekuatan kaki.",
        "Kurangi pegangan secara bertahap sampai bisa tanpa bantuan.",
      ],
    },
  },
  {
    id: "weighted-squat",
    nama: "Weighted Squat (Goblet/Backpack)",
    kategori: ["kaki", "fullbody"],
    alat: ["botol air / dumbbell"],
    deskripsi:
      "Squat dengan beban di depan dada (goblet) atau backpack berat.",
    langkah: [
      "PERSIAPAN: Pilih beban — dumbbell dipegang di depan dada (goblet) atau backpack diisi 5-15 kg dipakai di depan.",
      "POSISI AWAL: Berdiri tegak, kaki selebar bahu, ujung kaki sedikit keluar.",
      "Pegang beban dekat dada. Siku mengarah ke bawah.",
      "TURUN: Tarik napas. Dorong pinggul ke belakang, tekuk lutut.",
      "Turunkan sampai paha sejajar lantai atau lebih rendah.",
      "Punggung tetap tegak — beban di depan membantu keseimbangan.",
      "NAIK: Buang napas. Dorong melalui tumit, kembali berdiri.",
      "Kencangkan bokong di posisi atas.",
      "SELESAI: Letakkan beban perlahan setelah set selesai.",
    ],
    kesalahanUmum: [
      "Punggung membungkuk karena beban — Solusi: dada terbuka, beban dekat tubuh.",
      "Tumit terangkat — Solusi: berat di tumit, bisa taruh buku tipis di bawah tumit.",
    ],
    tips: [
      "Tambah beban perlahan — kaki cepat adaptasi.",
      "Squat + protein = metabolisme naik = perut rata.",
    ],
    videoEmbedId: "jGUXhDyUsmQ",
    prMetric: "reps",
  },
  {
    id: "bulgarian-split-squat",
    nama: "Bulgarian Split Squat",
    kategori: ["kaki"],
    alat: ["kursi / meja"],
    deskripsi:
      "Squat 1 kaki dengan kaki belakang di atas kursi. Membentuk paha & glutes.",
    langkah: [
      "POSISI AWAL: Berdiri 1 langkah besar di depan kursi. Menghadap MENJAUHI kursi.",
      "Angkat kaki belakang ke atas kursi — punggung kaki atau jari kaki menumpu di tepi kursi.",
      "Kaki depan kokoh di lantai, kaki selebar pinggul.",
      "Dada tegak, tangan di pinggul atau lurus ke samping untuk keseimbangan.",
      "TURUN: Tarik napas. Tekuk lutut kaki depan, turunkan tubuh.",
      "Turunkan sampai paha depan sejajar lantai. Lutut kaki depan TIDAK melebihi jari kaki (terlalu jauh).",
      "Lutut kaki belakang turun mendekati lantai.",
      "NAIK: Buang napas. Dorong melalui tumit kaki depan, kembali berdiri.",
      "Selesaikan semua rep di satu sisi, baru pindah kaki.",
      "SELESAI: Turunkan kaki belakang dari kursi, istirahat.",
    ],
    kesalahanUmum: [
      "Kaki depan terlalu dekat kursi — Solusi: ambil jarak lebih jauh.",
      "Badan condong ke depan — Solusi: dada tegak, pandangan ke depan.",
      "Lutut kaki depan melampaui jari kaki — Solusi: mundurkan kaki depan.",
    ],
    tips: [
      "Beban kebanyakan di kaki depan.",
      "Tambah backpack untuk beban tambahan.",
    ],
    videoEmbedId: "2C-uNgKwPLE",
    prMetric: "reps",
    alternatifTanpaAlat: {
      nama: "Reverse Lunge (Tanpa Kursi)",
      deskripsi: "Lunge mundur melatih otot yang sama dengan Bulgarian split squat tanpa butuh kursi.",
      langkah: [
        "Berdiri tegak, kaki rapat.",
        "MUNDUR: Langkahkan satu kaki ke belakang, turunkan lutut belakang mendekati lantai.",
        "Paha depan sejajar lantai, lutut depan tidak melewati jari kaki.",
        "NAIK: Dorong melalui tumit kaki depan, kembali berdiri.",
        "Bergantian kaki, atau selesaikan satu sisi dulu.",
        "Tambah backpack untuk beban tambahan.",
      ],
    },
  },
  {
    id: "concentration-curl",
    nama: "Concentration Curl",
    kategori: ["bisep"],
    alat: ["botol air / dumbbell"],
    deskripsi:
      "Bicep curl 1 tangan dengan siku ditopang paha. Isolasi murni untuk bisep.",
    langkah: [
      "POSISI AWAL: Duduk di kursi, buka kaki lebar. Badan condong sedikit ke depan.",
      "Pegang dumbbell/botol dengan SATU tangan. Siku tangan tersebut ditopang ke paha bagian dalam.",
      "Lengan menggantung lurus ke bawah. Ini posisi awal.",
      "ANGKAT: Buang napas. Tekuk siku, angkat beban perlahan ke arah bahu.",
      "HANYA lengan bawah yang bergerak. Siku dan lengan atas tetap diam (ditopang paha).",
      "Di posisi atas, PERAS bisep sekeras mungkin. Tahan 2 detik — rasakan peak contraction.",
      "TURUN: Tarik napas. Turunkan beban SANGAT PELAN (4 detik) ke posisi awal.",
      "Selesaikan semua rep di satu tangan, lalu pindah ke tangan lain.",
      "SELESAI: Letakkan beban, rilekskan.",
    ],
    kesalahanUmum: [
      "Mengayun beban dengan momentum — Solusi: tempo sangat pelan, siku terkunci di paha.",
      "Siku bergerak dari paha — Solusi: tekan siku ke paha sepanjang gerakan.",
      "Tidak peras di atas — Solusi: tahan 2 detik di peak, fokus mind-muscle connection.",
    ],
    tips: [
      "Pelan-pelan banget. Fokus mind-muscle connection.",
      "Ini adalah favorit Arnold Schwarzenegger untuk bisep tinggi.",
    ],
    videoEmbedId: "bQghTsfCiMw",
    prMetric: "reps",
  },
  {
    id: "preacher-curl-floor",
    nama: "Preacher-style Curl (di Kursi)",
    kategori: ["bisep"],
    alat: ["botol air / dumbbell", "kursi / meja"],
    deskripsi:
      "Bicep curl dengan siku ditopang sandaran kursi. Eliminates momentum.",
    langkah: [
      "POSISI AWAL: Berlutut di lantai di belakang kursi. Taruh siku & lengan atas di atas sandaran kursi (atau tepi tempat tidur).",
      "Pegang dumbbell/botol dengan satu tangan. Lengan bawah menggantung di sisi lain kursi.",
      "Lengan atas menempel penuh di sandaran kursi — ini mencegah kecurangan (cheating).",
      "ANGKAT: Buang napas. Tekuk siku, angkat beban ke arah bahu.",
      "Peras bisep di posisi atas. Tahan 1-2 detik.",
      "TURUN: Tarik napas. Turunkan beban PELAN (3 detik) sampai lengan hampir lurus.",
      "Jangan luruskan siku sepenuhnya di bawah — jaga sedikit bengkok untuk tegangan konstan.",
      "Selesaikan semua rep, pindah tangan.",
      "SELESAI: Letakkan beban.",
    ],
    kesalahanUmum: [
      "Lengan atas terangkat dari sandaran — berarti pakai momentum. Solusi: tekan lengan atas ke sandaran.",
      "Turun terlalu cepat — Solusi: hitung 3 detik saat turun.",
    ],
    tips: [
      "Versi tanpa-bench dari preacher curl di gym.",
      "Bagus banget untuk peak bisep.",
    ],
    videoEmbedId: "7v7uldi1eLU",
    prMetric: "reps",
    alternatifTanpaAlat: {
      nama: "Floor Concentration Curl (Duduk di Lantai)",
      deskripsi: "Concentration curl duduk di lantai — siku ditopang oleh lutut, tidak perlu kursi.",
      langkah: [
        "Duduk di lantai dengan kaki ditekuk, telapak kaki rata.",
        "Pegang dumbbell/botol dengan satu tangan. Taruh siku di bagian dalam lutut.",
        "ANGKAT: Tekuk siku, angkat beban ke bahu. Peras bisep 1-2 detik.",
        "TURUN: Turunkan pelan 3 detik. Ulangi, lalu pindah tangan.",
      ],
    },
  },
  {
    id: "diamond-pushup-feet-elevated",
    nama: "Decline Diamond Push-up",
    kategori: ["tricep", "dada"],
    alat: ["kursi / meja", "matras"],
    deskripsi:
      "Diamond push-up dengan kaki di kursi. Salah satu latihan tricep terkeras tanpa alat.",
    langkah: [
      "POSISI AWAL: Taruh kaki di kursi stabil. Tangan di lantai membentuk berlian (ibu jari & telunjuk menyentuh).",
      "Tubuh lurus diagonal dari kaki (atas) ke kepala. Core kencang.",
      "TURUN: Tarik napas. Tekuk siku ke BELAKANG, turunkan dada ke arah tangan.",
      "Turunkan serendah mungkin — rasakan tricep sangat tegang.",
      "Jeda 1 detik.",
      "NAIK: Buang napas, dorong kembali ke posisi awal dengan kekuatan tricep.",
      "SELESAI: Turunkan kaki dari kursi setelah set selesai.",
    ],
    kesalahanUmum: [
      "Siku terbuka ke samping — Solusi: siku ke belakang dekat badan.",
      "Tidak turun cukup dalam — Solusi: lower = more tricep activation.",
    ],
    tips: [
      "Maksimum tension ke tricep.",
      "Hanya lakukan setelah diamond push-up biasa terasa mudah.",
    ],
    videoEmbedId: "J0DnG1_S92I",
    prMetric: "reps",
    alternatifTanpaAlat: {
      nama: "Close-grip Diamond Push-up (di Lantai)",
      deskripsi: "Diamond push-up biasa di lantai — tetap menarget tricep tanpa butuh kursi untuk elevasi.",
      langkah: [
        "Posisi push-up biasa, tangan rapat membentuk berlian (ibu jari & telunjuk menyentuh).",
        "Tubuh lurus dari kepala ke tumit.",
        "TURUN: Tekuk siku ke belakang, turunkan dada ke arah tangan.",
        "NAIK: Dorong kembali ke posisi awal.",
        "Untuk tambah intensitas: pause 3 detik di posisi bawah.",
      ],
      videoEmbedId: "J0DnG1_S92I",
    },
  },
  {
    id: "tuck-front-lever",
    nama: "Tuck Front Lever Hold",
    kategori: ["punggung", "perut"],
    alat: ["tanpa alat"],
    deskripsi:
      "Gantung di bar dengan kaki ditarik ke dada, tubuh paralel dengan lantai. Latihan punggung & core advanced.",
    langkah: [
      "POSISI AWAL: Gantung di pull-up bar dengan grip overhand selebar bahu.",
      "Lengan lurus. Aktifkan scapula (tarik bahu ke bawah).",
      "MASUK POSISI: Tarik lutut ke dada (tuck). Putar tubuh ke belakang sehingga punggung menjadi PARALEL dengan lantai.",
      "Lengan tetap lurus. Badan seperti tergantung horizontal.",
      "TAHAN: Kencangkan punggung (lats), perut, dan bokong.",
      "Bernapas teratur.",
      "Jaga posisi paralel — jangan biarkan pinggul jatuh.",
      "Tahan selama target waktu.",
      "SELESAI: Putar kembali ke posisi gantung vertikal. Lepas bar.",
    ],
    kesalahanUmum: [
      "Pinggul jatuh di bawah bar — Solusi: aktifkan lats lebih kuat, tarik bar ke arah pinggul.",
      "Hanya tahan 1-2 detik — Solusi: ini normal, progres pelan-pelan.",
    ],
    tips: [
      "Sangat advanced. Coba setelah bulan 4.",
      "Mulai dari 5 detik. Goal 30 detik.",
    ],
    videoEmbedId: "BwhZYpIdhro",
    prMetric: "durasi-detik",
  },
  {
    id: "dragon-flag-progression",
    nama: "Dragon Flag Progression",
    kategori: ["perut"],
    alat: ["matras"],
    deskripsi:
      "Latihan perut legendaris dari Bruce Lee. Sangat brutal untuk lower abs.",
    langkah: [
      "PERSIAPAN: Tiduran terlentang di matras dekat sofa/kasur yang kuat. Raih ke belakang dan pegang pinggir sofa/kasur dengan kedua tangan.",
      "ANGKAT: Buang napas. Angkat SELURUH tubuh lurus ke atas seperti lilin — hanya bahu & kepala yang menyentuh lantai.",
      "Tubuh lurus dari bahu sampai kaki.",
      "TURUN: Tarik napas. Turunkan tubuh PELAN-PELAN dalam posisi lurus — seperti pisau lipat yang menutup perlahan.",
      "Hanya bahu yang tetap di lantai — punggung TIDAK boleh menyentuh lantai sampai rep selesai.",
      "Turunkan sampai tubuh hampir sejajar lantai, tapi jangan sampai menyentuh.",
      "NAIK KEMBALI: Buang napas, angkat kembali ke posisi lilin.",
      "VERSI PEMULA: Tekuk lutut (tuck dragon flag) — lebih mudah dan tetap efektif.",
      "SELESAI: Di rep terakhir, turunkan tubuh perlahan sampai lantai.",
    ],
    kesalahanUmum: [
      "Punggung menyentuh lantai saat turun — Solusi: kurangi range of motion, atau gunakan versi tuck.",
      "Hanya kaki yang bergerak, badan diam — Solusi: tubuh harus bergerak sebagai satu unit lurus.",
    ],
    tips: [
      "Progres: tuck (lutut ditekuk) → straddle → full straight.",
      "5 rep sudah luar biasa berat.",
    ],
    videoEmbedId: "At0mMAHqWrQ",
    prMetric: "reps",
  },
  {
    id: "explosive-push-up",
    nama: "Explosive / Clap Push-up",
    kategori: ["dada", "fullbody"],
    alat: ["matras"],
    deskripsi:
      "Push-up dengan dorong meledak — tangan terangkat dari lantai. Bangun power.",
    langkah: [
      "POSISI AWAL: Posisi push-up standar. Tangan selebar bahu, tubuh lurus.",
      "TURUN: Tarik napas, turunkan tubuh perlahan seperti push-up biasa.",
      "Turunkan sampai dada hampir menyentuh lantai.",
      "DORONG EXPLOSIF: Buang napas KUAT, dorong lantai sekuat-kuatnya sehingga TANGAN TERANGKAT dari lantai.",
      "CLAP (opsional): Jika tangan cukup tinggi, tepuk tangan 1x di udara.",
      "MENDARAT: Tangan kembali mendarat di posisi semula. Siku sedikit ditekuk untuk meredam benturan.",
      "Langsung masuk ke rep berikutnya.",
      "SELESAI: Setelah set selesai, turunkan lutut perlahan.",
    ],
    kesalahanUmum: [
      "Mendarat dengan siku kaku/lurus — bahaya pergelangan tangan. Solusi: mendarat dengan siku sedikit ditekuk.",
      "Tidak cukup power — tangan tidak terangkat. Solusi: kuasai dulu 15+ push-up standar.",
    ],
    tips: [
      "Hanya setelah bisa 15 push-up murni.",
      "Clap push-up versi lebih sulit — coba kalau sudah expert.",
    ],
    videoEmbedId: "FRo3b_Pfw3M",
    prMetric: "reps",
  },
  {
    id: "burpee-pullup",
    nama: "Burpee + Pull-up",
    kategori: ["fullbody", "kardio"],
    alat: ["tanpa alat"],
    deskripsi: "Kombinasi paling brutal — burpee selesai dengan 1 pull-up.",
    langkah: [
      "POSISI AWAL: Berdiri di bawah pull-up bar.",
      "BURPEE: Jongkok, taruh tangan di lantai, lompat kaki ke belakang (plank), lakukan 1 push-up.",
      "Lompat kaki ke depan, berdiri.",
      "PULL-UP: Dari posisi berdiri, lompat raih pull-up bar. Lakukan 1 pull-up murni.",
      "Turunkan tubuh, lepas bar.",
      "MENDARAT: Mendarat dengan lutut ditekuk.",
      "Langsung masuk rep berikutnya.",
      "SELESAI: Istirahat. Napas akan sangat cepat.",
    ],
    kesalahanUmum: [
      "Form hancur karena kelelahan — Solusi: kurangi rep tapi jaga form.",
      "Skip pull-up karena capek — Solusi: lakukan chin-up (lebih mudah) sebagai alternatif.",
    ],
    tips: [
      "Hanya untuk fase advanced (bulan 5-6).",
      "5 rep sudah membakar.",
    ],
    videoEmbedId: "qLBImHhCXSw",
    prMetric: "reps",
  },
  {
    id: "skip-rope",
    nama: "Skipping Rope",
    kategori: ["kardio"],
    alat: ["tanpa alat"],
    deskripsi:
      "Kardio paling efisien & murah. 10 menit skipping ≈ 30 menit jogging.",
    langkah: [
      "PERSIAPAN: Ukur panjang tali — injak tengah tali, pegangan harus sampai ketiak.",
      "POSISI AWAL: Berdiri tegak, kaki rapat. Pegang pegangan tali di kedua tangan.",
      "Siku dekat badan, lengan atas diam. Putaran tali datang dari PERGELANGAN TANGAN, bukan lengan.",
      "LOMPAT: Putar tali ke depan. Saat tali mendekati kaki, lompat kecil (2-5 cm cukup).",
      "Mendarat di ujung kaki (ball of foot), BUKAN tumit.",
      "Lutut sedikit ditekuk sepanjang gerakan.",
      "Jaga irama — tali berputar teratur, lompatan konsisten.",
      "Bernapas teratur: hirup melalui hidung, hembuskan melalui mulut.",
      "SELESAI: Perlambat putaran, lalu berhenti. Jalan di tempat untuk cool down.",
    ],
    kesalahanUmum: [
      "Lompatan terlalu tinggi — boros energi. Solusi: 2-5 cm sudah cukup.",
      "Tangan berputar dari bahu — Solusi: putar dari pergelangan tangan saja.",
      "Mendarat flat foot — Solusi: mendarat di ujung kaki.",
    ],
    tips: [
      "Pemula: 30 detik on, 30 detik off, ulangi 8-10 putaran.",
      "Setelah lancar: double under (tali putar 2x per lompatan).",
    ],
    videoEmbedId: "1BZM2Vre5oc",
    prMetric: "durasi-detik",
  },

  // =========== HAND GRIP EXERCISES ===========
  {
    id: "hand-grip-basic",
    nama: "Hand Grip — Squeeze Dasar",
    kategori: ["lengan"],
    alat: ["hand grip"],
    deskripsi:
      "Latihan dasar memperkuat genggaman dan lengan bawah (forearm). Cocok untuk pemula — mulai dari resistance terendah.",
    langkah: [
      "POSISI AWAL: Pegang hand grip dengan satu tangan, jari melingkari handle dengan rapat.",
      "SQUEEZE: Tekan handle sampai rapat/mentok dengan tenaga penuh. Tahan 1-2 detik.",
      "LEPAS PERLAHAN: Buka genggaman secara terkontrol (jangan langsung lepas). Ini bagian eccentric yang penting.",
      "ULANGI: Lakukan semua rep di satu tangan dulu, baru pindah ke tangan lainnya.",
      "BREATHING: Buang napas saat squeeze, tarik napas saat buka.",
      "Set resistance ke level terendah (5-10kg) untuk pemanasan, lalu naikkan sesuai kemampuan.",
    ],
    kesalahanUmum: [
      "Terlalu cepat — squeeze dan buka harus terkontrol, bukan asal remas.",
      "Skip tangan non-dominan — selalu latih kedua tangan dengan rep yang sama.",
      "Resistance terlalu berat sehingga tidak bisa squeeze penuh.",
    ],
    tips: [
      "Pemula: 5-15kg, fokus rep tinggi (15-20 per set).",
      "Intermediate: 20-35kg, rep 10-15.",
      "Advanced: 40-60kg, rep 8-12.",
      "Latihan ini bisa dilakukan sambil nonton TV atau di sela istirahat.",
    ],
    videoEmbedId: "uv48RVFR8GY",
    prMetric: "reps",
  },
  {
    id: "hand-grip-hold",
    nama: "Hand Grip — Crush Hold",
    kategori: ["lengan"],
    alat: ["hand grip"],
    deskripsi:
      "Tahan genggaman di posisi tertutup selama mungkin. Melatih daya tahan (endurance) genggaman — penting untuk pull-up dan hanging.",
    langkah: [
      "POSISI AWAL: Pegang hand grip, squeeze sampai handle rapat.",
      "TAHAN: Pertahankan posisi handle rapat/tertutup selama target waktu. Jaga tekanan konstan.",
      "BREATHING: Napas normal — jangan tahan napas.",
      "LEPAS: Kalau sudah tidak kuat menahan, buka perlahan.",
      "Ulangi di tangan satunya dengan durasi yang sama.",
      "Set resistance lebih ringan dari squeeze biasa (sekitar 60-70% dari max kamu).",
    ],
    tips: [
      "Target: mulai dari 15 detik hold, naikkan ke 30-60 detik.",
      "Kalau bisa hold >45 detik, naikkan resistance.",
      "Sangat bagus untuk persiapan dead hang & pull-up.",
    ],
    prMetric: "durasi-detik",
  },
  {
    id: "hand-grip-pulse",
    nama: "Hand Grip — Quick Pulse",
    kategori: ["lengan"],
    alat: ["hand grip"],
    deskripsi:
      "Squeeze cepat berulang-ulang untuk membangun daya tahan otot forearm dan meningkatkan aliran darah ke lengan.",
    langkah: [
      "POSISI: Pegang hand grip dengan resistance ringan-sedang (50-60% dari max).",
      "PULSE: Squeeze cepat dan buka — ritme cepat tapi tetap squeeze penuh tiap rep.",
      "TEMPO: Sekitar 1 detik per rep (squeeze-buka = 1 rep).",
      "Lanjutkan sampai forearm terasa terbakar (burning sensation) — itu tandanya efektif.",
      "Istirahat, lalu pindah ke tangan satunya.",
    ],
    tips: [
      "Jangan pakai resistance terlalu berat — ini latihan endurance, bukan max strength.",
      "Target 25-50 rep per set.",
      "Bagus sebagai finisher di akhir Pull day.",
    ],
    prMetric: "reps",
  },
];

export function getExercise(id: string): Exercise | undefined {
  return EXERCISES.find((e) => e.id === id);
}
